# Vagrantfile for multi-VM setup
Vagrant.configure("2") do |config|
    # Define VM web01
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/focal64" # Ubuntu 20.04
      web01.vm.hostname = "web01"
      web01.vm.network "private_network", ip: "192.168.56.41"
    end
  
    # Define VM web02
    config.vm.define "web02" do |web02|
      web02.vm.box = "ubuntu/focal64" # Ubuntu 20.04
      web02.vm.hostname = "web02"
      web02.vm.network "private_network", ip: "192.168.56.42"
    end

    # Define VM web02
    config.vm.define "web03" do |web03|
        web03.vm.box = "ubuntu/focal64" # Ubuntu 20.04
        web03.vm.hostname = "web02"
        web03.vm.network "private_network", ip: "192.168.56.44"
      end
  
    # Define VM db01
    config.vm.define "db01" do |db01|
      db01.vm.box = "centos/7" # CentOS 7
      db01.vm.hostname = "db01"
      db01.vm.network "private_network", ip: "192.168.56.43"
      db01.vm.provision "shell", inline: <<-SHELL
        yum install -y mariadb-server
        systemctl start mariadb
        systemctl enable mariadb
        # echo "Provisioning completed for db01."
      SHELL
    end
  end
  